SUPABASE_URL = "https://exerfrcrspvewzrbwjvv.supabase.co"

SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZXJmcmNyc3B2ZXd6cmJ3anZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkwNzA3NTMsImV4cCI6MjA5NDY0Njc1M30.PGHpiGxl80wLFmlKp9F8kwlMLkJjwzhc13k6_xSiQyw"